# Build steps common to all platforms

steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(NODE_VERSION)
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
    command: custom
    customCommand: install -g npm
  displayName: 'Update npm'
  condition: variables['UPGRADE_NPM']
  # Upgrade npm included in Node 6.x and 9.x as they don't include the `ci` command

- script: npm ci
  displayName: 'Install dependencies'

- script: npm run lint
  displayName: 'Linter'
  condition: eq(variables.test_suite, 'coverage')

- script: npm run $(test_suite) -- --reporter mocha-junit-reporter --reporter-options mochaFile=./test-results.xml
  displayName: 'Run tests'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/test-results.xml'
    testRunTitle: $(os_name) Node $(NODE_VERSION)
  displayName: 'Publishing the test results'
  condition: always()

- bash: npm run coveralls
  displayName: 'Run coveralls'
  condition: eq(variables.test_suite, 'coverage')
