jobs:

- job: Windows
  pool:
    vmImage: vs2017-win2016

  variables:
    os_name: Windows
    test_suite: unit

  strategy:
    matrix:
      node_6_x:
        node_version: 6.x
      node_8_x:
        node_version: 8.x
      node_9_x:
        node_version: 9.x
      node_10_x:
        node_version: 10.x
    maxParallel: 3

  steps:
  - template: .azure-pipelines-steps.yml

- job: Linux
  pool:
    vmImage: 'Ubuntu 16.04'

  variables:
    os_name: Linux
    test_suite: unit

  strategy:
    matrix:
      node_6_x:
        node_version: 6.x
      node_8_x:
        node_version: 8.x
        test_suite: coverage
        run_coverage: true
      node_9_x:
        node_version: 9.x
      node_10_x:
        node_version: 10.x
    maxParallel: 3

  steps:
  - template: .azure-pipelines-steps.yml

- job: OSX
  pool:
    vmImage: 'macOS 10.13'

  variables:
    os_name: OSX
    test_suite: unit

  strategy:
    matrix:
      node_6_x:
        node_version: 6.x
      node_8_x:
        node_version: 8.x
      node_9_x:
        node_version: 9.x
      node_10_x:
        node_version: 10.x
    maxParallel: 3

  steps:
  - template: .azure-pipelines-steps.yml
