// Generated by CoffeeScript 1.3.3
(function() {
  var fs, readJSONFile;

  fs = require('fs');

  readJSONFile = function(file, callback) {
    return fs.readFile(file, function(err, data) {
      var obj;
      obj = {};
      try {
        data = data.toString();
        obj = JSON.parse(data);
      } catch (error) {
        callback(error, null);
        return;
      }
      return callback(null, obj);
    });
  };

  module.exports.readJSONFile = readJSONFile;

}).call(this);
